In [ ]:
import tensorflow as tf
import keras
from keras.layers import Dense
from keras.models import Sequential
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split


In [ ]:
X,y = make_moons(n_samples = 250, noise = 0.05,random_state = 42)


In [ ]:
X.shape

(250, 2)

In [ ]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0])

In [ ]:
plt.scatter(X[:,0], X[:,1], c=y, s=100 )
plt.show()

In [ ]:
'''model = Sequential()
model.add(Dense(10, activation='sigmoid',input_dim = 2 ))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(10, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))'''

"model = Sequential()\nmodel.add(Dense(10, activation='sigmoid',input_dim = 2 ))\nmodel.add(Dense(10, activation='sigmoid'))\nmodel.add(Dense(10, activation='sigmoid'))\nmodel.add(Dense(10, activation='sigmoid'))\nmodel.add(Dense(10, activation='sigmoid'))\nmodel.add(Dense(10, activation='sigmoid'))\nmodel.add(Dense(10, activation='sigmoid'))\nmodel.add(Dense(10, activation='sigmoid'))\nmodel.add(Dense(10, activation='sigmoid'))\nmodel.add(Dense(10, activation='sigmoid'))\nmodel.add(Dense(10, activation='sigmoid'))\nmodel.add(Dense(1, activation='sigmoid'))"

In [ ]:

#using relu function

model = Sequential()
model.add(Dense(10, activation='relu',input_dim = 2, kernel_initializer= 'he_normal' ))
model.add(Dense(10, activation='relu',kernel_initializer= 'he_normal'))
model.add(Dense(10, activation='relu',kernel_initializer= 'he_normal'))
model.add(Dense(10, activation='relu',kernel_initializer= 'he_normal'))
model.add(Dense(10, activation='relu',kernel_initializer= 'he_normal'))
model.add(Dense(10, activation='relu',kernel_initializer= 'he_normal'))
model.add(Dense(1, activation='sigmoid'))


In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
old_weights = model.get_weights()[0]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
model.fit(X_train,y_train, epochs=100)

Epoch 1/100
7/7 [==============================] - 2s 6ms/step - loss: 0.7510 - accuracy: 0.3050
Epoch 2/100
7/7 [==============================] - 0s 4ms/step - loss: 0.7002 - accuracy: 0.3350
Epoch 3/100
7/7 [==============================] - 0s 4ms/step - loss: 0.6641 - accuracy: 0.5000
Epoch 4/100
7/7 [==============================] - 0s 5ms/step - loss: 0.6427 - accuracy: 0.5100
Epoch 5/100
7/7 [==============================] - 0s 5ms/step - loss: 0.6261 - accuracy: 0.5100
Epoch 6/100
7/7 [==============================] - 0s 4ms/step - loss: 0.6113 - accuracy: 0.5150
Epoch 7/100
7/7 [==============================] - 0s 4ms/step - loss: 0.5960 - accuracy: 0.5700
Epoch 8/100
7/7 [==============================] - 0s 5ms/step - loss: 0.5784 - accuracy: 0.6650
Epoch 9/100
7/7 [==============================] - 0s 5ms/step - loss: 0.5603 - accuracy: 0.7150
Epoch 10/100
7/7 [==============================] - 0s 4ms/step - loss: 0.5423 - accuracy: 0.7200
Epoch 11/100
7/7 [===========

In [ ]:
new_weights = model.get_weights()[0]

In [ ]:
old_weights

array([[-1.4338747 ,  1.05614   ,  0.5961106 ,  0.24701968, -1.3961269 ,
        -1.4331526 ,  0.07444198,  1.0663806 , -0.85671145, -1.4731885 ],
       [-0.9533676 , -0.3310426 ,  0.3105977 , -1.5508355 ,  0.03000715,
        -1.4954399 , -0.32788917, -0.29322532, -0.06513578,  1.0705743 ]],
      dtype=float32)

In [ ]:
new_weights

array([[-1.5448489 ,  1.0480715 ,  0.67201465,  0.28201017, -1.362148  ,
        -1.4215487 ,  0.1552509 ,  0.9884107 , -0.831545  , -1.5625173 ],
       [-0.85104734, -0.33512098,  0.42684838, -1.7572632 , -0.00450325,
        -1.5040992 , -0.22237585, -0.5150186 , -0.04299008,  1.2370509 ]],
      dtype=float32)

In [ ]:
percent_change = abs((new_weights - old_weights)/old_weights)*100

In [ ]:
percent_change

array([[  7.739462  ,   0.76395583,  12.733219  ,  14.165062  ,
          2.4337916 ,   0.8096718 , 108.55291   ,   7.31164   ,
          2.9375646 ,   6.0636344 ],
       [ 10.732509  ,   1.231983  ,  37.42806   ,  13.31074   ,
        115.00725   ,   0.5790512 ,  32.179565  ,  75.63919   ,
         33.999287  ,  15.550216  ]], dtype=float32)

In [ ]:
from mlxtend.plotting import plot_decision_regions
plot_decision_regions(X_train, y_train.astype('int'),clf = model, legend = 2)

9600/9600 [==============================] - 18s 2ms/step


<Axes: >